[general]
import = [
  "~/.config/alacritty/themes/themes/solarized_dark.toml"
  # "~/.config/alacritty/themes/themes/solarized_light.toml"
]

[terminal]
shell = { program = "/bin/bash" }

[cursor] 
style = { shape = "Block", blinking = "On" }

[font]
size = 18


