[general]
import = [
  # "~/.config/alacritty/themes/themes/solarized_dark.toml"
  # "~/.config/alacritty/themes/themes/solarized_light.toml"
  "~/.config/alacritty/themes/themes/solarized_osaka.toml"
]

[terminal]
shell = { program = "zellij" }

[cursor]
style = { shape = "Block", blinking = "On" }

[font]
size = 11
normal = { family = "BlexMonoNerdFont", style = "Regular" }


